<!-- Wrapper End -->
<script type="text/javascript" src="{{asset('frontend/js/jquery-3.3.1.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/jquery-migrate-3.0.0.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/jquery.mmenu.all.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/ace-responsive-menu.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/isotop.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/snackbar.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/simplebar.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/parallax.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/scrollto.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/jquery-scrolltofixed-min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/jquery.counterup.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/wow.min.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/progressbar.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/slider.js') }}"></script>
<script type="text/javascript" src="{{asset('frontend/js/timepicker.js') }}"></script>
<!-- Custom script for all pages -->
<script type="text/javascript" src="{{asset('frontend/js/script.js') }}"></script>
